# 1. Phân tích văn bản thành Token

## 1.1 Regular Expression

In [26]:
def load_doc(filename):
    file = open(filename, 'r')
    text = file.read()
    file.close()
    return text
def load_vndoc(filename):
    file = open(filename, 'r', encoding="utf-8")
    text = file.read()
    file.close()
    return text

In [19]:

text = "I'm 1.5 meters tall. What about you? Don't say you are higher than me."
text

"I'm 1.5 meters tall. What about you? Don't say you are higher than me."

In [20]:
import re
tokens = re.split(r'[-\s.,;!?)(]+', text)
print(tokens)

["I'm", '1', '5', 'meters', 'tall', 'What', 'about', 'you', "Don't", 'say', 'you', 'are', 'higher', 'than', 'me', '']


## 1.2 RegexpTokenizer (English & Vietnamese)

In [21]:
from nltk.tokenize import RegexpTokenizer 
tokenizer_2 = RegexpTokenizer(r'\w+|$[0-9.]+|\S+')
token_2 = tokenizer_2.tokenize(text)
print(token_2)

['I', "'m", '1', '.5', 'meters', 'tall', '.', 'What', 'about', 'you', '?', 'Don', "'t", 'say', 'you', 'are', 'higher', 'than', 'me', '.']


## 1.3 TreebankWordTokenizer

In [23]:
# better
from nltk.tokenize import TreebankWordTokenizer
tokenizer_3 = TreebankWordTokenizer()
print(tokenizer_3.tokenize(text))

['I', "'m", '1.5', 'meters', 'tall.', 'What', 'about', 'you', '?', 'Do', "n't", 'say', 'you', 'are', 'higher', 'than', 'me', '.']


## 1.4 ```casual_tokenize```

In [24]:
from nltk.tokenize.casual import casual_tokenize
message = "Wowwww! I can't believe you can do that! Suprising! Suhhhhhhhhhhh! Keep silent plez!"
print(casual_tokenize(message))
print(tokenizer_3.tokenize(message))
print(casual_tokenize(message, reduce_len=True, strip_handles = True))

['Wowwww', '!', 'I', "can't", 'believe', 'you', 'can', 'do', 'that', '!', 'Suprising', '!', 'Suhhhhhhhhhhh', '!', 'Keep', 'silent', 'plez', '!']
['Wowwww', '!', 'I', 'ca', "n't", 'believe', 'you', 'can', 'do', 'that', '!', 'Suprising', '!', 'Suhhhhhhhhhhh', '!', 'Keep', 'silent', 'plez', '!']
['Wowww', '!', 'I', "can't", 'believe', 'you', 'can', 'do', 'that', '!', 'Suprising', '!', 'Suhhh', '!', 'Keep', 'silent', 'plez', '!']


## 1.5 pyvi.ViTokenizer cho Tiếng Việt

In [25]:
from pyvi import ViTokenizer
text_vn = load_vndoc('D:/Documents/CODEBOOK/Course/text_vn_1.txt')
print(ViTokenizer.tokenize(text_vn).split())

['USD', 'điều_chỉnh', 'trái', 'chiều', ',', 'vàng', 'SJC', 'quay', 'đầu', 'tăng', 'Mỗi', 'lượng', 'vàng', 'SJC', 'sáng', 'nay', 'tăng', '20.000', 'đồng', 'sau', 'khi', 'vừa', 'có', 'phiên', 'đi', 'xuống', ';', 'tỷ_giá', 'trung_tâm', 'được', 'Ngân_hàng', 'Nhà_nước', 'tăng', '10', 'đồng', 'nhưng', 'các', 'nhà', 'băng', 'lại', 'giảm', '.', 'Mở_cửa', 'đầu', 'ngày', '23', '/', '11', ',', 'Tập_đoàn', 'DOJI', 'niêm_yết_giá', 'vàng', 'miếng', 'SJC', 'cao', 'hơn', '20.000', 'đồng', 'một', 'lượng', 'so', 'với', 'hôm_qua', 'với', 'giá', 'mua_bán', '36,44', '-', '36,54', 'triệu', 'đồng', '.', 'Tương_tự', ',', 'các', 'doanh_nghiệp', 'vàng', 'khác', 'trong', 'nước', 'cũng', 'tăng', 'vài', 'chục', 'nghìn', 'đồng', 'một', 'lượng', 'và', 'dao_động', 'quanh', 'mốc', '36,5', 'triệu', 'đồng', '.', 'Giao_dịch', 'vàng', 'tại', 'doanh_nghiệp', 'PNJ.', 'Ảnh', ':', 'Lệ_Chi', '.', 'Giao_dịch', 'vàng', 'tại', 'doanh_nghiệp', 'PNJ.', 'Ảnh', ':', 'Lệ_Chi', '.', 'Sự', 'đi', 'lên', 'nhẹ', 'của', 'giá', 'vàng', 'tron

## 1.6 underthesea.word_tokenize cho Tiếng Việt

In [29]:
#better
from underthesea import word_tokenize
print(word_tokenize(text_vn))

['USD', 'điều chỉnh', 'trái', 'chiều', ',', 'vàng', 'SJC', 'quay', 'đầu', 'tăng', 'Mỗi', 'lượng', 'vàng', 'SJC', 'sáng', 'nay', 'tăng', '20.000', 'đồng', 'sau', 'khi', 'vừa', 'có', 'phiên', 'đi', 'xuống', ';', 'tỷ giá', 'trung tâm', 'được', 'Ngân hàng', 'Nhà nước', 'tăng', '10', 'đồng', 'nhưng', 'các', 'nhà băng', 'lại', 'giảm', '.', 'Mở cửa', 'đầu', 'ngày', '23/11', ',', 'Tập đoàn', 'DOJI', 'niêm yết giá', 'vàng', 'miếng', 'SJC', 'cao', 'hơn', '20.000', 'đồng', 'một', 'lượng', 'so', 'với', 'hôm qua', 'với', 'giá', 'mua bán', '36,44', '-', '36,54', 'triệu', 'đồng', '.', 'Tương tự', ',', 'các', 'doanh nghiệp', 'vàng', 'khác', 'trong', 'nước', 'cũng', 'tăng', 'vài', 'chục', 'nghìn', 'đồng', 'một', 'lượng', 'và', 'dao động', 'quanh', 'mốc', '36,5', 'triệu', 'đồng', '.', 'Giao dịch', 'vàng', 'tại', 'doanh nghiệp', 'PNJ. Ảnh', ':', 'Lệ Chi', '.', 'Giao dịch', 'vàng', 'tại', 'doanh nghiệp', 'PNJ. Ảnh', ':', 'Lệ Chi', '.', 'Sự', 'đi', 'lên', 'nhẹ', 'của', 'giá', 'vàng', 'trong', 'nước', 'cũng

# 2. Chuyển text thành vector

## 2.1 n-grams

sử dụng hàm ```zip()```

In [2]:
import re
def generate_ngrams_1(text, n):
    text = text.lower()
    tokens = re.split(r'[-.,?!;)()\s]+', text)
    tokens = [token for token in tokens if token!= ""]
    ngrams = zip(*[tokens[i:] for i in range(n)])
    return [" ".join(ngram) for ngram in ngrams]
s = "cô ấy không thích trà"
generate_ngrams_1(s, n=2)

['cô ấy', 'ấy không', 'không thích', 'thích trà']

sử dụng nltk.util.ngrams

In [4]:
from nltk.util import ngrams
def generate_ngrams_2(text, n):
    text = text.lower()
    tokens = re.split(r'[-.,?!;)()\s]+', text)
    tokens = [token for token in tokens if token!= ""]
    output = list(ngrams(tokens, n))
    output = [' '.join(i) for i in output]
    return output
s = "cô ấy không thích trà"
generate_ngrams_2(s, n=2)

['cô ấy', 'ấy không', 'không thích', 'thích trà']

## 2.2 Bag-of-words

sử dụng CountVectorizer

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.toarray())
print(vectorizer.get_feature_names())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


Kết hợp CountVectorizer với n-grams

In [7]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]
vectorizer_2 = CountVectorizer(ngram_range = (1, 2))
Y = vectorizer_2.fit_transform(corpus)
print(Y.toarray())
print(vectorizer_2.get_feature_names())

[[0 0 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0]
 [0 0 2 1 0 0 1 1 0 0 1 1 1 0 1 0 0 0 1 1 0 0]
 [1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 1 1 0 1 0]
 [0 0 1 0 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1]]
['and', 'and this', 'document', 'document is', 'first', 'first document', 'is', 'is the', 'is this', 'one', 'second', 'second document', 'the', 'the first', 'the second', 'the third', 'third', 'third one', 'this', 'this document', 'this is', 'this the']


## 2.3 TF-IDF

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
# list of text documents
text = ["The quick brown fox jumped over the lazy dog.",
		"The dog.",
		"The fox"]
# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)
# encode document
vector = vectorizer.transform([text[0]])
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
[1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]
(1, 8)
[[0.36388646 0.27674503 0.27674503 0.36388646 0.36388646 0.36388646
  0.36388646 0.42983441]]


# 3. Mô hình Logistic Regression cho bài toán phân loại

Dưới đây là quá trình xây dựng mô hình Logistic Regression để phân loại sắc thái bình luận (neg/pos) với dữ liệu là các comment trên twitter

## 3.1 tải dữ liệu

In [31]:
import numpy as np
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/dhminh1024/practice_datasets/master/twitter_sentiment_analysis.csv', encoding='latin-1')
data.head()

ItemID  Sentiment                                      SentimentText
0       1          0                       is so sad for my APL frie...
1       2          0                     I missed the New Moon trail...
2       3          1                            omg its already 7:30 :O
3       4          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4       5          0           i think mi bf is cheating on me!!!   ...

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99989 entries, 0 to 99988
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   ItemID         99989 non-null  int64 
 1   Sentiment      99989 non-null  int64 
 2   SentimentText  99989 non-null  object
dtypes: int64(2), object(1)
memory usage: 2.3+ MB


## 3.2 Xử lý dữ liệu

### 3.2.1 Stemming

Dùng cho tiếng Anh để nhóm các từ cùng kiểu vd: do, did, done thành một từ 

In [44]:
from nltk.stem import PorterStemmer

porter = PorterStemmer()

def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [46]:
from collections import Counter
vocab = Counter()
for tweet in data.SentimentText:
    tweet = tokenizer_porter(tweet)
    for word in tweet:
        vocab[word]+=1
        
# before processing
vocab.most_common(20)

[('I', 32880),
 ('the', 29630),
 ('to', 28812),
 ('you', 23471),
 ('a', 21321),
 ('i', 16000),
 ('and', 15826),
 ('it', 15228),
 ('my', 12385),
 ('for', 12378),
 ('in', 11199),
 ('is', 11185),
 ('that', 10920),
 ('have', 10566),
 ('of', 10326),
 ('on', 9021),
 ('but', 8489),
 ('me', 8255),
 ("i'm", 8167),
 ('be', 7944)]

### 3.2.2 Loại bỏ từ không quan trọng 

Từ không quan trọng (stopword) là những từ xuất hiện nhiều nhưng nó hầu như không mang ý nghĩa (vd: the, is, that,...)

In [47]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [48]:
clean_vocab= Counter()
for word, c in vocab.items():
    if word not in stop_words:
        clean_vocab[word]=c
# after cleaning
clean_vocab.most_common(20)

[('I', 32880),
 ("i'm", 8167),
 ('wa', 7137),
 ('get', 6470),
 ('like', 5646),
 ('go', 5498),
 ('love', 5003),
 ('good', 4955),
 ('-', 4922),
 ('thank', 4610),
 ('thi', 4364),
 ("it'", 4309),
 ('u', 4195),
 ('know', 3701),
 ('lol', 3505),
 ('see', 3349),
 ('one', 3188),
 ('think', 3129),
 ('hope', 3098),
 ('want', 3019)]

### 3.2.3 Loại bỏ ký tự đặc biệt trừ emoji

In [49]:
import re 

def preprocessor(text):
    """ Return a cleaned version of text
    """
    # Remove HTML markup
    text = re.sub('<[^>]*>', '', text)
    # Save emoticons for later appending
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    # Remove any non-word character and append the emoticons,
    # removing the nose character for standarization. Convert to lower case
    text = (re.sub('[\W]+', ' ', text.lower()) + ' ' + ' '.join(emoticons).replace('-', ''))
    
    return text

# Create some random texts for testing the function preprocessor()
print(preprocessor('I like it :), |||<><>'))

i like it  :)


## 3.3 Build Model

In [52]:
from sklearn.model_selection import train_test_split

X = data['SentimentText']
y = data['Sentiment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=102)

sử dụng pipeline để kết hợp các bước từ số hóa dữ liệu -> tạo mô hình học từ dữ liệu

Các bước thực hiện trong Pipeline bao gồm:
- Loại bỏ stopwords
- stemming các comment
- loại bỏ ký tự đặc biệt trừ Emoji
- Tạo vector tfidf 
- Huấn luyện Logistic Regression từ vector tfidf

In [53]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words=stop_words,
                        tokenizer=tokenizer_porter,
                        preprocessor=preprocessor)

# A pipeline is what chains several steps together, once the initial exploration is done. 
# For example, some codes are meant to transform features — normalise numericals, or turn text into vectors, 
# or fill up missing data, they are transformers; other codes are meant to predict variables by fitting an algorithm,
# they are estimators. Pipeline chains all these together which can then be applied to training data
clf = Pipeline([('vect', tfidf),
                ('clf', LogisticRegression(random_state=0))])
clf.fit(X_train, y_train)

D:\softwares\anaconda\lib\site-packages\sklearn\feature_extraction\text.py:301: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'ani', 'becaus', 'befor', 'doe', 'dure', 'ha', 'hi', 'onc', 'onli', 'ourselv', 'themselv', 'thi', 'veri', 'wa', 'whi', 'yourselv'] not in stop_words.
  'stop_words.' % sorted(inconsistent))
D:\softwares\anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2',
        preprocessor=<function prepr...e, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False))])

## 3.4 Đánh giá mô hình

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Now apply those above metrics to evaluate your model
# Your code here
predictions = clf.predict(X_test)
print('accuracy:',accuracy_score(y_test,predictions))
print('confusion matrix:\n',confusion_matrix(y_test,predictions))
print('classification report:\n',classification_report(y_test,predictions))

accuracy: 0.7520252025202521
confusion matrix:
 [[5814 2891]
 [2068 9225]]
classification report:
               precision    recall  f1-score   support

           0       0.74      0.67      0.70      8705
           1       0.76      0.82      0.79     11293

   micro avg       0.75      0.75      0.75     19998
   macro avg       0.75      0.74      0.74     19998
weighted avg       0.75      0.75      0.75     19998



## 3.5 Dự đoán

In [55]:
twits = [
    "I do not feel not bad", # Phuc +1
    'This model is "so good" :))', # Long -1
    'we are who we are', # Nghi 0
    'its good to be bad sometimes', # PA +1
    'what a wonderful failure! (sarcasm :)))', #Phuc +1
    'People do not like the bad things', # Chi 0
    'We finally have the test result. You are positive', # Long +1
]

preds = clf.predict_proba(twits)

for i in range(len(twits)):
    print(f'{twits[i]} --> Negative, Positive = {preds[i]}')

I do not feel not bad --> Negative, Positive = [0.99056371 0.00943629]
This model is "so good" :)) --> Negative, Positive = [0.16056502 0.83943498]
we are who we are --> Negative, Positive = [0.38855991 0.61144009]
its good to be bad sometimes --> Negative, Positive = [0.53694825 0.46305175]
what a wonderful failure! (sarcasm :))) --> Negative, Positive = [0.30184744 0.69815256]
People do not like the bad things --> Negative, Positive = [0.78125783 0.21874217]
We finally have the test result. You are positive --> Negative, Positive = [0.20088749 0.79911251]
